In [ ]:
#numpy example
import numpy as np
a = np.array([1,2,3,4])
print(a)
b = np.array([[1,2,3],[4,5,6]])
print(b)
# 3 element in a array
print(a[0],a[1],a[2])
#2 element in the b array
print(b[0,0],b[0,1],b[1,0])
# 0 to 2 index in a array
print(a[0:1],a[1:3])

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
1 2 3
1 2 4
[1] [2 3]


In [4]:
# create an array with 50 elements and each should have different combinations
import numpy as np
a = np.arange(50)
print(a)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [14]:
#addition in two array with large numbers
import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a+b)
print(a[0]+a[3])
#add elements in only one array
print(a+1)


[ 6  8 10 12]
5
[2 3 4 5]


In [15]:
#negative indexing example using array
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[1,-1])

10


In [20]:
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'Brand': ['Maruti', 'Hyundai', 'Tata', 'Mahindra', 'Maruti', 'Hyundai',
              'Renault', 'Tata', 'Maruti'],
    'Year': [2012, 2014, 2011, 2015, 2012, 2016, 2014, 2018, 2019],
    'Kms Driven': [50000, 30000, 60000, 25000, 10000, 46000, 31000, 15000, 12000],
    'City': ['Gurgaon', np.nan, 'Mumbai', 'Delhi', 'Mumbai', 'Delhi',
             'Mumbai', 'Chennai', 'Ghaziabad'],
    'Mileage': [28, 27, 25, 26, 28, 29, 24, 21, 24]
})

# Display the DataFrame
display(data)

# Filter where Brand is 'Maruti' and Year is 2012
display(data.loc[(data['Brand'] == 'Maruti') & (data['Year'] == 2012)])

# Filter where Brand is 'Hyundai' and 'Kms Driven' > 30000
display(data.loc[(data['Brand'] == 'Hyundai') & (data['Kms Driven'] > 30000)])

# Filter where City is 'Delhi' and 'Kms Driven' > 30000
display(data.loc[(data['City'] == 'Delhi') & (data['Kms Driven'] > 30000)])

# Creating another DataFrame for joins
customers = pd.DataFrame({
    'Brand': ['Maruti', 'Hyundai', 'Tata', 'Mahindra', 'Renault'],
    'Customer Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Discount Amount': [5000, 7000, 4500, 8000, 6000]
})

# Inner Join
result_inner = pd.merge(data, customers, on='Brand', how='inner')
display(result_inner)

# Left Join
result_left = pd.merge(data, customers, on='Brand', how='left')
display(result_left)

# Right Join
result_right = pd.merge(data, customers, on='Brand', how='right')
display(result_right)

# Outer Join
result_outer = pd.merge(data, customers, on='Brand', how='outer')
display(result_outer)


Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1   Hyundai  2014       30000        NaN       27
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       28
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       24
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24

Brand  Year  Kms Driven     City  Mileage
0  Maruti  2012       50000  Gurgaon       28
4  Maruti  2012       10000   Mumbai       28

Brand  Year  Kms Driven   City  Mileage
5  Hyundai  2016       46000  Delhi       29

Brand  Year  Kms Driven   City  Mileage
5  Hyundai  2016       46000  Delhi       29

Brand  Year  Kms Driven       City  Mileage Customer Name  \
0    Maruti  2012       50000    Gurgaon       28         Alice   
1   Hyundai  2014       30000        NaN       27           Bob   
2      Tata  2011       60000     Mumbai       25       Charlie   
3  Mahindra  2015       25000      Delhi       26         David   
4    Maruti  2012       10000     Mumbai       28         Alice   
5   Hyundai  2016       46000      Delhi       29           Bob   
6   Renault  2014       31000     Mumbai       24           Eve   
7      Tata  2018       15000    Chennai       21       Charlie   
8    Maruti  2019       12000  Ghaziabad       24         Alice   

   Discount Amount  
0             5000  
1             7000  
2             4500  
3             8000  
4             5000  
5             7000  
6             6000  
7             4500  
8             5000

Brand  Year  Kms Driven       City  Mileage Customer Name  \
0    Maruti  2012       50000    Gurgaon       28         Alice   
1   Hyundai  2014       30000        NaN       27           Bob   
2      Tata  2011       60000     Mumbai       25       Charlie   
3  Mahindra  2015       25000      Delhi       26         David   
4    Maruti  2012       10000     Mumbai       28         Alice   
5   Hyundai  2016       46000      Delhi       29           Bob   
6   Renault  2014       31000     Mumbai       24           Eve   
7      Tata  2018       15000    Chennai       21       Charlie   
8    Maruti  2019       12000  Ghaziabad       24         Alice   

   Discount Amount  
0             5000  
1             7000  
2             4500  
3             8000  
4             5000  
5             7000  
6             6000  
7             4500  
8             5000

Brand  Year  Kms Driven       City  Mileage Customer Name  \
0    Maruti  2012       50000    Gurgaon       28         Alice   
1    Maruti  2012       10000     Mumbai       28         Alice   
2    Maruti  2019       12000  Ghaziabad       24         Alice   
3   Hyundai  2014       30000        NaN       27           Bob   
4   Hyundai  2016       46000      Delhi       29           Bob   
5      Tata  2011       60000     Mumbai       25       Charlie   
6      Tata  2018       15000    Chennai       21       Charlie   
7  Mahindra  2015       25000      Delhi       26         David   
8   Renault  2014       31000     Mumbai       24           Eve   

   Discount Amount  
0             5000  
1             5000  
2             5000  
3             7000  
4             7000  
5             4500  
6             4500  
7             8000  
8             6000

Brand  Year  Kms Driven       City  Mileage Customer Name  \
0   Hyundai  2014       30000        NaN       27           Bob   
1   Hyundai  2016       46000      Delhi       29           Bob   
2  Mahindra  2015       25000      Delhi       26         David   
3    Maruti  2012       50000    Gurgaon       28         Alice   
4    Maruti  2012       10000     Mumbai       28         Alice   
5    Maruti  2019       12000  Ghaziabad       24         Alice   
6   Renault  2014       31000     Mumbai       24           Eve   
7      Tata  2011       60000     Mumbai       25       Charlie   
8      Tata  2018       15000    Chennai       21       Charlie   

   Discount Amount  
0             7000  
1             7000  
2             8000  
3             5000  
4             5000  
5             5000  
6             6000  
7             4500  
8             4500